dist: trusty
sudo: false

branches:
  only:
    - master

env:
  # This environment variable tells Terraform not to prompt for input. This is
  # not required, but if we make a mistake, the Travis builder will hang waiting
  # for user input, tieing up unnecessary resources.
  - TF_INPUT=false

# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
  - wget https://github.com/wata727/tflint/releases/download/v0.7.0/tflint_linux_amd64.zip
  - unzip tflint_linux_amd64.zip
  - mkdir -p /usr/local/tflint/bin
  - export PATH=/usr/local/tflint/bin:$PATH
  - install tflint /usr/local/tflint/bin

script:
  - terraform init
  - terraform plan
  - tflint main.tf